// src/components/header/Header.vue
<template>
  <header class="header">
    <!-- PC 메뉴 -->
    <nav v-if="!isMobile">
      <button v-if="showBackButton" class="back-btn" @click="goBack" lang="en">Back</button>
      <ul>
        <li><button @click="scrollTo('about')" lang="en">About</button></li>
        <li><button @click="scrollTo('education')" lang="en">Career</button></li>
        <li><button @click="scrollTo('skill')" lang="en">Skill</button></li>
        <li><button @click="scrollTo('project')" lang="en">Project</button></li>
      </ul>
    </nav>

    <!-- 모바일 메뉴 -->
    <nav v-else class="mo-nav">
      <font-awesome-icon icon="fa-solid fa-bars" class="mo-menu" @click="menuOn" />

      <ul class="mo-menu__inner glass">
        <li><button @click="scrollTo('about')" lang="en">About</button></li>
        <li><button @click="scrollTo('education')" lang="en">Career</button></li>
        <li><button @click="scrollTo('skill')" lang="en">Skill</button></li>
        <li><button @click="scrollTo('project')" lang="en">Project</button></li>
        <li>
          <font-awesome-icon icon="fa-solid fa-xmark" class="close-btn" @click="menuOff" />
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  data() {
    return {
      isMobile: false,
      isScrolled: false,
    }
  },

  computed: {
    showBackButton() {
      return this.$route.path === '/gstt-detail'
    },
  },
  methods: {
    // 뒤로가기
    goBack() {
      if (window.history.length > 1) {
        this.$router.back()
      } else {
        this.$router.push({ path: '/' })
      }
    },
    // 스크롤 해당 섹션으로 이동
    scrollTo(id) {
      const section = document.getElementById(id)
      if (section) {
        section.scrollIntoView({ behavior: 'smooth' })
      }
      if (this.isMobile) {
        this.menuOff()
      }
    },

    // 메뉴 열기
    menuOn() {
      const menu = document.querySelector('.mo-menu__inner')
      const hamburger = document.querySelector('.mo-menu')
      menu.classList.add('active')
      hamburger.style.display = 'none'
      document.body.style.overflow = 'hidden'
    },

    // 메뉴 닫기
    menuOff() {
      const menu = document.querySelector('.mo-menu__inner')
      const hamburger = document.querySelector('.mo-menu')
      document.body.style.overflow = 'auto'
      menu.classList.remove('active')
      menu.classList.add('closing')

      menu.addEventListener(
        'animationend',
        () => {
          menu.classList.remove('closing')
          hamburger.style.display = 'block'
        },
        { once: true },
      )
    },

    // 스크롤 내렸을때 헤더
    scrollDown() {
      const header = document.querySelector('.header')
      const hamburger = document.querySelector('.mo-menu')
      const scrolled = window.scrollY > 100

      if (scrolled !== this.isScrolled) {
        this.isScrolled = scrolled

        if (this.isScrolled) {
          header.classList.add('active')
          if (hamburger) hamburger.style.color = '#fff'
        } else {
          header.classList.remove('active')
          if (hamburger) hamburger.style.color = '#fff'
        }
      }
    },
  },

  // 모바일 감지 + 스크롤 이벤트
  mounted() {
    const userAgent = navigator.userAgent.toLowerCase()
    this.isMobile = /iphone|ipad|ipod|android/.test(userAgent)

    window.addEventListener('scroll', this.scrollDown, { passive: true })
    this.scrollDown()
  },
  beforeUnmount() {
    window.removeEventListener('scroll', this.scrollDown)
  },
}
</script>

<style lang="scss">
header {
  position: sticky;
  top: 0;
  height: 85px;
  border-bottom: 1px solid $border;
  z-index: 3;

  nav {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    height: inherit;

    ul {
      display: flex;
      width: 100%;
      text-align: right;
      justify-content: flex-end;
      margin: 0 3rem;
      z-index: 5;

      li {
        display: flex;
        justify-content: flex-end;
        margin-right: 5rem;

        &:last-child {
          margin-right: 0;
        }

        button {
          color: $white;
          -webkit-text-fill-color: $white;
          font-size: 2.3rem;
          transition: -webkit-text-fill-color 3s ease-in-out;

          &:hover {
            background-image: $point-color;
            background-size: 200% 100%;
            background-position: 0% 0;
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            animation: gradientMove 1s ease-in-out;
          }
        }
      }
    }

    .back-btn {
      margin-right: auto;
      margin-left: 3rem;
      background: none;
      border: none;
      color: $white;
      font-size: 2.3rem;
      cursor: pointer;
      transition: color 0.3s ease;

    
    }
      }
    }

  &::before {
    content: '';
    position: absolute;
    inset: 0;
    pointer-events: none;
    opacity: 0;
    backdrop-filter: blur(12px) saturate(120%);
    -webkit-backdrop-filter: blur(12px) saturate(120%);
  }

  &.active::before {
    animation: glassIn 0.3s ease forwards;
  }

  &:not(.active)::before {
    animation: glassOut 0.3s ease forwards;
  }

  // 모바일 메뉴
  .mo-nav {
    width: 95%;
    margin: 0 auto;
    font-size: 2.5rem;
    position: relative;
    z-index: 2;

    .mo-menu__inner {
      position: fixed;
      flex-direction: column;
      top: 0;
      right: -100%;
      margin: 0;
      visibility: hidden;
      opacity: 0;

      &.glass {
        @include glass(100%, 100%, 4px, 180%, 2rem, #fff);
        border-radius: 0;
        padding: 10rem 0 0 0;
        justify-content: flex-start;
        align-items: flex-end;
      }

      &.active {
        visibility: visible;
        opacity: 1;
        animation: menuOpen 0.3s forwards;
      }

      &.closing {
        visibility: visible;
        opacity: 1;
        animation: menuClose 0.3s forwards;
      }

      li {
        font-size: 2.8rem;
        margin-bottom: 2rem;
        button {
          text-shadow: 4px 4px 4px rgba(0, 0, 0, 0.25);
        }
        &:last-child {
          margin-bottom: 0;
        }
        .fa-xmark {
          position: absolute;
          right: 30px;
          top: 30px;
          font-size: 2rem;
        }
      }
    }
  }

@keyframes gradientMove {
  from {
    background-position: 0% 0;
  }
  to {
    background-position: 100% 0;
  }
}

@keyframes menuOpen {
  0% {
    right: -100%;
  }
  100% {
    right: 0;
  }
}

@keyframes menuClose {
  0% {
    right: 0;
  }
  100% {
    right: -100%;
  }
}

@keyframes glassIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
@keyframes glassOut {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}
</style>

// src/components/header/Header.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBars, faXmark } from '@fortawesome/free-solid-svg-icons'
import { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'

import styles from '/assets/scss/components/header/Header.module.scss'
import mediaStyles from '/assets/scss/components/header/HeaderMedia.module.scss'

const Header = () => {
  const location = useLocation()
  const navigate = useNavigate()
  const [isMobile, setIsMobile] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)
  const showBackButton = location.pathname === '/gstt-detail'

  // 768px 이하 모바일 UI 전환
  const checkMobile = () => {
    const userAgent = navigator.userAgent.toLowerCase()
    const isMobileDevice = /iphone|ipad|ipod|android/.test(userAgent)
    setIsMobile(window.matchMedia('(max-width: 768px)').matches || isMobileDevice)
  }

  // 뒤로가기
  const goBack = () => {
    if (window.history.length > 1) {
      navigate(-1)
    } else {
      navigate('/')
    }

    window.setTimeout(() => {
      window.scrollTo({ top: 0, left: 0, behavior: 'auto' })
    }, 0)
  }

  // 해당 섹션으로 이동
  const scrollTo = (id: string) => {
    const section = document.getElementById(id)
    if (section) {
      section.scrollIntoView({ behavior: 'smooth' })
    }
    if (isMobile) {
      menuOff()
    }
  }

  // 메뉴 열기
  const menuOn = () => {
    const menu = document.querySelector<HTMLElement>(`.${styles['mo-menu__inner']}`)
    const hamburger = document.querySelector<HTMLElement>(`.${styles['mo-menu']}`)

    if (!menu || !hamburger) return

    menu.classList.add(styles.active)
    hamburger.style.display = 'none'
    document.body.style.overflow = 'hidden'
  }

  // 메뉴 닫기
  const menuOff = () => {
    const menu = document.querySelector<HTMLElement>(`.${styles['mo-menu__inner']}`)
    const hamburger = document.querySelector<HTMLElement>(`.${styles['mo-menu']}`)

    if (!menu || !hamburger) return

    document.body.style.overflow = 'auto'
    menu.classList.remove(styles.active)
    menu.classList.add(styles.closing)

    menu.addEventListener(
      'animationend',
      () => {
        menu.classList.remove(styles.closing)
        hamburger.style.display = 'block'
      },
      { once: true },
    )
  }

  // 스크롤 후 헤더 스타일
  const scrollDown = () => {
    const scrolled = window.scrollY > 100
    setIsScrolled(scrolled)
  }

  // 모바일 감지 및 스크롤 이벤트
  useEffect(() => {
    checkMobile()
    scrollDown()

    window.addEventListener('scroll', scrollDown, { passive: true })
    window.addEventListener('resize', checkMobile)

    return () => {
      window.removeEventListener('scroll', scrollDown)
      window.removeEventListener('resize', checkMobile)
      document.body.style.overflow = 'auto'
    }
  }, [])

  const menuItems = [
    { id: 'about', label: 'About' },
    { id: 'journey', label: 'Career' },
    { id: 'skill', label: 'Skill' },
    { id: 'project', label: 'Project' },
  ]

  return (
    <header
      className={`${styles['portfolio-header']} ${styles['header']} ${mediaStyles['portfolio-header']} ${mediaStyles['header']} ${isScrolled ? styles.active : ''}`}
    >
      {showBackButton ? (
        <nav>
          <button className={styles['back-btn']} onClick={goBack} lang="en">
            Back
          </button>
        </nav>
      ) : !isMobile ? (
        <nav>
          <ul>
            {menuItems.map((item) => (
              <li key={item.id}>
                <button onClick={() => scrollTo(item.id)} lang="en">
                  {item.label}
                </button>
              </li>
            ))}
          </ul>
        </nav>
      ) : (
        <nav className={styles['mo-nav']}>
          <span className={styles['mo-menu']} onClick={menuOn}>
            <FontAwesomeIcon icon={faBars}></FontAwesomeIcon>
          </span>
          <ul className={`${styles['mo-menu__inner']} ${styles['glass']}`}>
            {menuItems.map((item) => (
              <li key={item.id}>
                <button onClick={() => scrollTo(item.id)} lang="en">
                  {item.label}
                </button>
              </li>
            ))}
            <li>
              <span onClick={menuOff}>
                <FontAwesomeIcon icon={faXmark}></FontAwesomeIcon>
              </span>
            </li>
          </ul>
        </nav>
      )}
    </header>
  )
}

export default Header
